### PR TITLE
Upgrade to net 8

### PR DESCRIPTION
**Pull request by bistok**
Here is the Pull Request for net 8

### CODE REVIEW

**Comment by bistok** [comment]
Yes there where many places that needed changes, let me check the conflicts

**Comment by bistok** [comment]
Fixed conflicts

**Comment by kgrzybek** [comment]
>Perhaps it's not my place to comment, but I believe that moving ICommand and IQuery to buildingblocks project may not be advisable. This is because you now lose IDE/build support for determining which commands and queries are permissible in each module, a feature that was previously available.

It is definitely good place to comment, @AlmarAubel and this is valid point.

@bistok Can you revert this particular change?

**Comment by kgrzybek** [comment]
@bistok I am checking your changes but general problem with .NET 8.0 is that is not supported by Rider https://rider-support.jetbrains.com/hc/en-us/articles/13244959138834 For instance tests cannot be executed...

For this reason, I'm suspending the merge to main and we have to wait for Rider support. Of course, after that we can merge, because a lot of work was done. 

I can help with autofac issue too. In one of the project we changed approach and used PipelineBehaviors of Mediatr instead of autofac decorators.

**Comment by bistok** [comment]
@kgrzybek I evaluated about changing to using the functionality on Mediatr, but not do it because that was a fundamental change from the code and the documentation need to be changed.

@AlmarAubel you could live with the ICommand and IQuery on buildingblocks? there almost 300 files that need changes to revert this back

**Comment by kgrzybek** [comment]
I upgraded to Rider 2023.3 and it is better. I need to check whether it is production ready.

@bistok We lose type check during command execution and this is important. Commands and Queries are public API of modules. Maybe would be better to do opposite -> applying changes from particular commits (cherry picks?) and do not apply this particular change.

Or maybe based on your pr I can do it myself :)

**Comment by bistok** [comment]
@kgrzybek I have the change almost ready, running integration test to validate

**Comment by bistok** [comment]
@kgrzybek I added logging to the test to debug the errors, I leave it or better remove it?

**Comment by kgrzybek** [comment]
@bistok Great work, @bistok 🥇 . Thank you very much. Everything looks fine, merged 👍 

I will add you both to main contributors page.

**Pull request merged**
