### PR TITLE
refactor: Use new  collection initializers

### PR DESCRIPTION
**Pull request by AlmarAubel**
I've made some updates in our codebase to leverage the new list initializer syntax introduced in C# 12. This change aims to enhance readability and maintainability of our code.

However, I encountered an issue with StyleCop. Currently, StyleCop has a known problem ([#3745](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/pull/3745), [#3687](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/3687)) that triggers SA01010 as a false positive when using this new syntax. Until this is resolved in StyleCop, we might see this warning.

I'd appreciate your feedback on these changes. Please share your thoughts  if you like this kind of pull request And if you're okay with the interim StyleCop warning we'll encounter.

### CODE REVIEW

**Comment by bistok** [comment]
I was tempted to do this change when migrated to .NET 8, but not do it because the Stylecop warnings, I see they merge the commit that fixed this and marked it to the next release, I think we can live some time because they will fix it when releasing the next package version.

**Comment by kgrzybek** [comment]
@AlmarAubel 

I really like this type of pull request.

However, the problem lies with these warnings. I want to treat this project to be **as close to the production implementation as possible**. In projects I participate in, we treat all warnings as errors, and I consider it a good practice. 

Therefore, I would prefer to wait with merging this pull request until a new version of StyleCop is released. WDYT?

**Comment by AlmarAubel** [comment]
Yes totally agree, at my professional projects we also treat warnings as errors. So let's wait. I will monitor the release of the new version of Stylecop and will add the version bump to this pr once released.

**Comment by kgrzybek** [comment]
Good, let's wait. 

Meanwhile, I removed all warnings and enabled "warnings as errors" in https://github.com/kgrzybek/modular-monolith-with-ddd/commit/fed5f5fd94c7a016cf2186204e4a65e1a253d7e6

**Comment by AlmarAubel** [comment]
I've resolved the issue using Stylecop and updated the package accordingly. Apologies for the additional commits resulting from an error while merging from master. I hope you can squash merge this commit to streamline the changes.

**Comment by kgrzybek** [comment]
Good job @AlmarAubel, thanks for the active monitoring of StyleCop repo!

**Pull request merged**
