### PR TITLE
Upgrade to net7.0

### PR DESCRIPTION
**Pull request by AlmarAubel**
- Upgrade all projects to .net 7.0
- Could not fully check docker because SQL Server can not still not run on a silicon Macbook 
- All tests still passes.
- Only update necessary packages

Fixes issue #264

### CODE REVIEW

**Comment by kgrzybek** [comment]
Hi @AlmarAubel 

Thanks for that PR. I will try to check it soon. It will be very valuable.

**Comment by AlmarAubel** [comment]
I also created a second branch to make it possible to run docker-compose (and in particular Mysql) on ARM (Macbook with silicon processor)  you can find it here -> https://github.com/AlmarAubel/modular-monolith-with-ddd/pull/2. If you like it I can create a PR on this repo.

**Comment by AlmarAubel** [comment]
@kgrzybek  I understand that you might be quite busy, but I was wondering if you could kindly spare some time to review my PR.  I would greatly appreciate your feedback

**Comment by kgrzybek** [comment]
@AlmarAubel Thank you very much, it's been a long time, but I'm back to developing this repo :)

**Pull request merged**
